use deku::{DekuContainerRead, DekuRead, DekuWrite, DekuWriter, writer::Writer};

use crate::utils::{
  FieldReader, FieldWriter, RadiotapError, RadiotapField, RadiotapFieldTrait,
  RadiotapFieldTraitIdentifiers,
};

/// Aggregated MAC Protocol Data Unit (A-MPDU) status field
///
/// The presence of this field indicates that the frame was received as part of an a-MPDU.
///
/// See [www.radiotap.org/fields/A-MPDU%20status.html](https://www.radiotap.org/fields/A-MPDU%20status.html)
/// for more information.
#[derive(Clone, Debug, Default, DekuRead, DekuWrite, PartialEq)]
#[deku(endian = "little", bit_order = "lsb")]
pub struct AmpduStatusField {
  /// Generated by the capture device and is the same across each subframe of an A-MPDU. Since the
  /// capture device might be capable of capturing multiple channels or data from multiple
  /// (concurrent) captures could be merged, the reference number is not guaranteed to be unique
  /// across different channels. As a result, applications should use the channel information
  /// together with the reference number to identify the subframes belonging to the same A-MPDU.
  pub reference_number: u32,

  /// Flags driver reports 0-length subframes
  #[deku(bits = "1")]
  pub flags_report_zerolen: bool,

  /// Flags frame is 0-length subframe (Valid only if `flags_report_zerolen` is set)
  #[deku(bits = "1")]
  pub flags_is_zerolen: bool,

  /// Flags last subframe is known (Should be set for all subframes in an A-MPDU)
  #[deku(bits = "1")]
  pub flags_last_known: bool,

  /// Flags last subframe
  #[deku(bits = "1")]
  pub flags_is_last: bool,

  /// Flags delimiter CRC error
  #[deku(bits = "1")]
  pub flags_delim_crc_err: bool,

  /// Flags delimiter CRC known
  #[deku(bits = "1")]
  pub flags_delim_crc_known: bool,

  /// Flags EOF value
  #[deku(bits = "1")]
  pub flags_eof: bool,

  /// Flags EOF value known
  #[deku(bits = "1")]
  pub flags_eof_known: bool,

  /// Flags reserved 0
  #[deku(bits = "8")]
  pub flags_reserved: u8,

  /// Delimiter CRC
  pub delimiter_crc: u8,

  /// Reserved 0
  pub reserved0: u8,
}

impl<V> RadiotapFieldTrait<V> for AmpduStatusField {
  fn get_identifiers(&self) -> RadiotapFieldTraitIdentifiers {
    RadiotapFieldTraitIdentifiers { bit_index: 20 }
  }

  fn get_alignment(&self) -> usize {
    4
  }

  fn decode(&self, reader: &mut FieldReader) -> Result<RadiotapField<V>, RadiotapError> {
    // Decode the field
    let decoded = AmpduStatusField::from_reader((reader, 0))?.1;

    Ok(RadiotapField::AmpduStatus(decoded))
  }

  fn encode(&self, writer: &mut Writer<&mut FieldWriter>) -> Result<(), RadiotapError> {
    // Encode the field
    self.to_writer(writer, ())?;

    Ok(())
  }
}

#[cfg(test)]
mod tests {
  use deku::{DekuContainerRead, DekuContainerWrite};
  use pretty_assertions::assert_eq;
  use rstest::rstest;

  use super::*;

  /// Encoding test cases
  const ENCODING_CASES: &[(&[u8], &AmpduStatusField)] = &[
    // No flags
    (
      &[
        0x21, 0x43, 0x34, 0x12, // Reference number
        0x00, 0x00, // Flags
        0xAB, // Delimiter CRC
        0x00, // Reserved
      ],
      &AmpduStatusField {
        reference_number: 0x12344321,
        flags_report_zerolen: false,
        flags_is_zerolen: false,
        flags_last_known: false,
        flags_is_last: false,
        flags_delim_crc_err: false,
        flags_delim_crc_known: false,
        flags_eof: false,
        flags_eof_known: false,
        flags_reserved: 0,
        delimiter_crc: 0xAB,
        reserved0: 0,
      },
    ),
    // Alternating flags (A)
    (
      &[
        0x21, 0x43, 0x34, 0x12, // Reference number
        0x55, 0x00, // Flags
        0xAB, // Delimiter CRC
        0x00, // Reserved
      ],
      &AmpduStatusField {
        reference_number: 0x12344321,
        flags_report_zerolen: true,
        flags_is_zerolen: false,
        flags_last_known: true,
        flags_is_last: false,
        flags_delim_crc_err: true,
        flags_delim_crc_known: false,
        flags_eof: true,
        flags_eof_known: false,
        flags_reserved: 0,
        delimiter_crc: 0xAB,
        reserved0: 0,
      },
    ),
    // Alternating flags (B)
    (
      &[
        0x21, 0x43, 0x34, 0x12, // Reference number
        0xAA, 0x00, // Flags
        0xAB, // Delimiter CRC
        0x00, // Reserved
      ],
      &AmpduStatusField {
        reference_number: 0x12344321,
        flags_report_zerolen: false,
        flags_is_zerolen: true,
        flags_last_known: false,
        flags_is_last: true,
        flags_delim_crc_err: false,
        flags_delim_crc_known: true,
        flags_eof: false,
        flags_eof_known: true,
        flags_reserved: 0,
        delimiter_crc: 0xAB,
        reserved0: 0,
      },
    ),
  ];

  #[rstest]
  #[case::no_flags(ENCODING_CASES[0].0, ENCODING_CASES[0].1)]
  #[case::alternating_flags_a(ENCODING_CASES[1].0, ENCODING_CASES[1].1)]
  #[case::alternating_flags_b(ENCODING_CASES[2].0, ENCODING_CASES[2].1)]
  fn test_decode_field(#[case] encoded: &[u8], #[case] expected: &AmpduStatusField) {
    // Decode the bytes
    let decoded = AmpduStatusField::from_bytes((encoded, 0)).unwrap().1;

    // Check the result
    assert_eq!(decoded, *expected);
  }

  #[rstest]
  #[case::no_flags(ENCODING_CASES[0].1, ENCODING_CASES[0].0)]
  #[case::alternating_flags_a(ENCODING_CASES[1].1, ENCODING_CASES[1].0)]
  #[case::alternating_flags_b(ENCODING_CASES[2].1, ENCODING_CASES[2].0)]
  fn test_encode_field(#[case] field: &AmpduStatusField, #[case] expected: &[u8]) {
    // Encode the field
    let encoded = field.to_bytes().unwrap();

    // Check the result
    assert_eq!(encoded, expected);
  }
}
