name: continuous integration
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install Rust toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add aarch64-unknown-none --toolchain stable

      - name: Lint code
        run: cargo clippy --all-targets --all-features -- --deny warnings

      - name: Audit dependencies
        uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project (std)
        run: cargo build --release

      - name: Build project (no_std)
        run: cargo build --target aarch64-unknown-none --release

      - name: Run tests
        run: cargo test --release
